### ISSUE TITLE
thfuck problem with Traceback (most recent call last):

### ISSUE THREAD

**Issue by LuoPX-15510486969** [nvbn/thefuck#331]
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 160, in main
    matched_rule = get_matched_rule(command, rules, settings)
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 105, in get_matched_rule
    script_only = command.stdout is None and command.stderr is None
AttributeError: 'NoneType' object has no attribute 'stdout'

OS : Ubuntu12.04
/usr/bin/python
/usr/local/bin/thefuck
six==1.9.0
<module 'six' from '/usr/local/lib/python2.7/dist-packages/six.pyc'>
1.9.0
True

**Comment by nvbn** [comment]
Probably fixed in 2.7.

**Comment by LuoPX-15510486969** [comment]
after upgrade to 2.7.still has the same problem.

**Comment by nvbn** [comment]
Is it ok with 2.8?
